Header header
float64 T		#delta T
float64 find_l		#hand's vertical angle delta (left)
float64 find_r		#hand's vertical angle delta (right
float32 fin_l		#hand's vertical angle (left)
float32 fin_r		#hand's vertical angle (right)
float32 dir_l		#hand direction (left)
float32 dir_r		#hand direction (right)
float32 length_l	#length (left)
float32 length_r	#length (right)
float32 shoulders	#shoulders width
